# Desktop-specific conf
{ config, pkgs, lib, ... }:

{
  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    nix-search-cli
    neovim 
    kitty
    alacritty
    foot
    wget
    jq
    fd
    alsa-utils
    htop
    neofetch
    sops
    git
    qpwgraph
    pwvucontrol
    wofi
    waybar
    ashell
    swaynotificationcenter
    swayosd
    libnotify
    procps
    sysstat
    lm_sensors
    acpi
    pciutils
    smartmontools
    fwupd
    age
    hyprpaper
    hyprpanel
    kdePackages.dolphin
    wl-clipboard
    wl-clip-persist
    clipse
    eww
    socat
    btop
    fastfetch
    discord
    gcc
    binutils
    ast-grep
    ripgrep
    fzf
    lazygit
    lua51Packages.lua
    nodejs_24
    zulu8
    go
    julia
    unzip
    tree-sitter
    luajitPackages.luarocks_bootstrap
    ghostscript
    gnumake
    cunit
    cmake
    ninja
    tectonic
    mermaid-cli
    sqlite
    python313
    python313Packages.pip
    python313Packages.pynvim
    cargo
    rustc
    rust-analyzer
    ccache
    llvmPackages_21.lld
    llvmPackages_21.llvm
    llvmPackages_21.clang
    lldb_21
    clang-tools
    aider-chat
    opencode
    codex
    gemini-cli
    exfat
    partclone
  ];

  fonts.packages = with pkgs; [
    font-awesome
    noto-fonts
    noto-fonts-emoji
    nerd-fonts.symbols-only
  ];
}
